version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:01"
      timezone: "US/Pacific"
    open-pull-requests-limit: 2
    reviewers:
      - "ericharper1"
    
