version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:21"
      timezone: "US/Pacific"
    open-pull-requests-limit: 2
    reviewers:
      - "ericharper1"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "disabled"
    target-branch: "add-dependabot"
    
